# Use a lightweight Nginx web server as the base image
FROM nginx:alpine

# Copy frontend files to the Nginx HTML directory
COPY . /usr/share/nginx/html

# Expose port 80 to serve the frontend
EXPOSE 80