services:
  semantic_analysis:
    build:
      context: .
      dockerfile: semantic_analysis/Dockerfile
    volumes:
      - raw_course_data:/job/semantic_analysis/data
    environment:
      # - FORCE_PARSE=${FORCE_PARSE:-false}
      # - FORCE_EMBED=${FORCE_EMBED:-false}
      - FORCE_PARSE=true
      - FORCE_EMBED=true
      - DB_IMPLEMENTATION=${DB_IMPLEMENTATION:-sqlite}
      - DB_PATH=${DB_PATH:-/job/semantic_analysis/data/semantic_analysis.db}
    depends_on:
      - ollama

  ollama:
      image: ollama/ollama
      container_name: ollama
      volumes:
        - ollama:/root/.ollama
      command: serve
      # expose:
      #  - 11434
      ports:
        - "11434:11434"

volumes:
  raw_course_data:
  ollama: